import React from "react";
import '../Miscellaneous/Scrollbar.css';

const HeatmapTable = () => {
  return (
    <>
      <table className="text-lg font-normal text-white font-poppins">
        <thead className="sticky top-0 ">
          <tr className="flex gap-7 py-4  justify-evenly bg-[rgb(16,16,16)] px-3 border border-white">
            <th className="">S.No</th>
            <th className="whitespace-nowrap">CBT1A1</th>
            <th className="whitespace-nowrap">CBT2A1</th>
            <th className="whitespace-nowrap">CBT3A1</th>
            <th className="whitespace-nowrap">CBT4A1</th>
            <th className="whitespace-nowrap">CBT5A1</th>
            <th className="whitespace-nowrap">CBT6A1</th>
            <th className="whitespace-nowrap">CBT7A1</th>
            <th className="whitespace-nowrap">CBT8A1</th>
            <th className="whitespace-nowrap">CBT9A1</th>
            <th className="whitespace-nowrap">CBT10A1</th>
            <th className="whitespace-nowrap">CBT11A1</th>
            <th className="whitespace-nowrap">CBT12A1</th>
            <th className="whitespace-nowrap">CBT13A1</th>
            <th className="whitespace-nowrap">CBT14A1</th>
            <th className="whitespace-nowrap">CBT15A1</th>
            <th className="whitespace-nowrap">CBT16A1</th>
            <th className="whitespace-nowrap">CBT17A1</th>
            <th className="whitespace-nowrap">CBT18A1</th>
            <th className="whitespace-nowrap">CBT19A1</th>
            <th className="whitespace-nowrap">CBT20A1</th>
            <th className="whitespace-nowrap">CBT21A1</th>
            <th className="whitespace-nowrap">CBT22A1</th>
            <th className="whitespace-nowrap">CBT23A1</th>
            <th className="whitespace-nowrap">CBT24A1</th>
          </tr>
        </thead>
        <tbody className="overflow-y-scroll scrollbar-custom">
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly items-center bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="whitespace-nowrap">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
          <tr className="flex px-3 py-2 border-t border-white gap-7 justify-evenly bg-[rgb(16,16,16)]">
            <td className="">1</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
            <td className="whitespace-nowrap">29</td>
            <td className="whitespace-nowrap">20</td>
            <td className="whitespace-nowrap">22</td>
            <td className="whitespace-nowrap">21</td>
            <td className="whitespace-nowrap">19</td>
            <td className="whitespace-nowrap">25</td>
            <td className="whitespace-nowrap">24</td>
            <td className="whitespace-nowrap">23</td>
            <td className="whitespace-nowrap">26</td>
            <td className="whitespace-nowrap">30</td>
            <td className="whitespace-nowrap">28</td>
            <td className="whitespace-nowrap">27</td>
          </tr>
        </tbody>
      </table>
    </>
  );
};

export default HeatmapTable;
